version: '3'
services:
    mysql:
        image: mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: app
    php-fpm:
        build: docker/php-fpm
        ports:
            - "9000:9001"
        volumes:
            - ./app:/var/www/app
        links:
            - mysql
        extra_hosts:
            - "docker-host.localhost:127.0.0.1"
    nginx:
        build: docker/nginx
        ports:
            - "8080:80"
        links:
            - php-fpm
        volumes:
            - ./app:/var/www/app
            - ./logs/nginx:/var/log/nginx
