index:
    path: /
    controller: App\Controller\IndexController::indexAction
image:
    path: /get/{name}
    requirements:
        name: .+
    controller: App\Controller\ImageController::imageAction